query($slug: String!) {
  location: allLocation(
    where: { slug: { current: { eq: $slug } } }
    sort: [{ _updatedAt: ASC }]
  ) {
    about: aboutRaw
    address {
      city
      state
      street
      zipcode
    }
    blurb: blurbRaw
    heroImage {
      alt
      asset {
        id: _id
        url
      }
      caption: captionRaw
      captionColor
    }
    heroVideo {
      url
    }
    hours
    meta: seo {
      description
      image {
        asset {
          url
        }
      }
      title
    }
    shortName
  }
}
