query {
  shopPage: ShopPage(id: "shopPage") {
    navigation {
      featuredCollections {
        displayName
        handle
      }
      regularCollections {
        displayName
        handle
      }
    }
  }
}
